
<br> 
<br>
<br>

#### Articles on Generalized Additive Models: methods and applications

   - Gioia, V., Fasiolo, M., Browell, J. and Bellio, R., 2024. Additive Covariance Matrix Models: Modeling Regional Electricity Net-Demand in Great Britain. Journal of the American Statistical Association, pp.1-13.
   
   - Amara-Ouali, Yvenn, Matteo Fasiolo, Yannig Goude, and Hui Yan. "Daily peak electrical load forecasting with a multi-resolution approach." International Journal of Forecasting 39, no. 3 (2023): 1272-1286.

   - Browell, J. and Fasiolo, M., 2021. Probabilistic Forecasting of Regional Net-load with Conditional Extremes and Gridded NWP. IEEE Transactions on Smart Grid, 12(6), pp.5011-5019.

   - Capezza, C., Palumbo, B., Goude, Y., Wood, S.N. and Fasiolo, M., 2021. Additive stacking for disaggregate electricity demand forecasting. The Annals of Applied Statistics, 15(2), pp.727-746.

   - Fasiolo, M., Wood, S.N., Zaffran, M., Nedellec, R. and Goude, Y., 2021. Fast calibrated additive quantile regression. Journal of the American Statistical Association, 116(535), pp.1402-1412.
   
   - Fasiolo, M., Wood, S. N., Zaffran, M., Nedellec, R., & Goude, Y. 2021. qgam: Bayesian Nonparametric Quantile Regression Modeling in R. Journal of Statistical Software, 100(9), 1–31. https://doi.org/10.18637/jss.v100.i09

   - Fasiolo, M., Nedellec, R., Goude, Y. and Wood, S.N., 2019. Scalable visualisation methods for modern Generalized Additive Models. Journal of Computational and Graphical Statistics.

   - Wood, S.N. and Fasiolo, M., 2017. A generalized Fellner‐Schall method for smoothing parameter optimization with application to Tweedie location, scale and shape models. Biometrics, 73(4), pp.1071-1081.
   
<br>
   
#### Articles on Monte Carlo methods, intractable likelihoods and other topics

   - Ward, D., Beaumont, M. and Fasiolo, M., 2024. SoftCVI: Contrastive variational inference with self-generated soft labels. Accepted as a "spotlight" paper at ICLR 2025, arXiv preprint arXiv:2407.15687.

   - Ward, D., Cannon, P., Beaumont, M., Fasiolo, M. and Schmon, S., 2022. Robust neural posterior estimation and statistical model criticism. Advances in Neural Information Processing Systems, 35, pp.33845-33859.

   - Fasiolo, M., de Melo, F.E. and Maskell, S., 2018. Langevin incremental mixture importance sampling. Statistics and Computing, 28(3), pp.549-561.
   
   - Fasiolo, M., Wood, S.N., Hartig, F. and Bravington, M.V., 2018. An extended empirical saddlepoint approximation for intractable likelihoods. Electronic Journal of Statistics, 12(1), pp.1544-1578.
   
   - Fasiolo, M., Pya, N. and Wood, S.N., 2016. A comparison of inferential methods for highly nonlinear state space models in ecology and epidemiology. Statistical Science, 31(1), pp.96-118.
   
<br>

#### Interdisciplinary publications

   - De Rosa, D., Ballabio, C., Lugato, E., Fasiolo, M., Jones, A. and Panagos, P., 2024. Soil organic carbon stocks in European croplands and grasslands: How much have we lost in the past decade?. Global Change Biology, 30(1), p.e16992.
   
  - de Vilmarest, J., Browell, J., Fasiolo, M., Goude, Y. and Wintenberger, O., 2023. Adaptive probabilistic forecasting of electricity (net-) load. IEEE Transactions on Power Systems, 39(2), pp.4154-4163.

   - Baayen, R.H., Fasiolo, M., Wood, S. and Chuang, Y.Y., 2022. A note on the modeling of the effects of experimental time in psycholinguistic experiments. The Mental Lexicon, 17(2), pp.178-212. arXiv preprint arXiv:2105.13786.

   - De Rosa, D., Basso, B., Fasiolo, M., Friedl, J., Fulkerson, B., Grace, P.R. and Rowlings, D.W., 2021. Predicting pasture biomass using a statistical model and machine learning algorithm implemented with remotely sensed imagery. Computers and Electronics in Agriculture, 180, p.105880.

   - Noacco, V., Duffy, C. J., Wagener, T., Worrall, F., Fasiolo, M. and Howden, N.J.K. (2019). Drivers of inter-and intra-annual variability of dissolved organic carbon concentration in the River Thames between 1884 and 2013. Hydrological processes. 33 (6), 994-1012.

   - Tomaschek, F., Tucker, B.V., Fasiolo, M. and Baayen, R.H., 2018. Practice makes perfect: The consequences of lexical proficiency for articulation. Linguistics Vanguard, 4(s2).



