
<style>
body {
text-align: justify}
</style>

<br> 

# Theory of Inference MATH35600/MATHM0019

<br> 

The course instructor is [Matteo Fasiolo](http://www.bristol.ac.uk/maths/people/matteo-fasiolo/overview.html) (Fry GA.17). There are 2 lectures and one computer lab-based tutorial each week (see BB page for details). 20% of the course mark will be from an assessed practical project. The remaining 80% comes from a 2.5 hour exam consisting of 4 questions (no choice): an example is provided below. Tutorial sheet questions provide the best preparation for the exam. Office hours are XXX (see BB page).

<br> 

#### Course material

The course will be based on the following material:

* [Lecture Notes](TOI/notes.pdf) These may be updated as the course progresses.
* [Matrix Notes](TOI/matrix.pdf) Essential revision notes on matrices.
* [Core Statistics](https://www.maths.ed.ac.uk/~swood34/core-statistics.pdf) is a short textbook covering the material in this course, along with background and extensions. Chapter one should be reviewed for the essential background assumed by the course.
* [JAGs manual](TOI/jags_user_manual.pdf) JAGS user manual is a handy reference for when we cover Bayesian computation. 

Further relevant books are:

* D.R. Cox (2006) *Principles of Statistical Inference* also covers much of the material in the course. 
* A.C. Davison (2003) *Statistical Models* covers everything we cover and much more.
* G. Casella and R.L Berger (1990) *Statistical Inference* covers many of the topics in greater mathematical depth.
* Daniel Kahneman's *Thinking Fast and Slow* has alot of interesting things to say about statistical reasoning, and the built in flaws in how we humans tend to reason and make inferences. 

If you need to brush up on basic matrix algebra and multivariate calculus, you might want to have a look at:

* [Basic matrix algebra](http://www.sosmath.com/matrix/matrix.html)
* [Simple matrix differentiation](https://en.wikibooks.org/wiki/Econometric_Theory/Matrix_Differentiation)
* [Simple explanation of multivariate Taylor expansion](https://mathinsight.org/taylors_theorem_multivariable_introduction)

These are some data sets that you might need during the course:

* [confound.txt](TOI/confound.txt)
* [urchin.vol.dat](TOI/urchin.vol.dat)
* [bccd.dat](TOI/bccd.dat)
* [sh-H1N1.dat](TOI/sh-H1N1.dat)
* [algae.dat](TOI/algae.dat)

You can load them in R using code such as:
```{r eval=FALSE}
dat <- read.table("https://mfasiolo.github.io/TOI/confound.txt")
```

Here is some code that we will use:

* [Bayes_conv.R](TOI/Bayes_conv.R)
* [Bootstrap.R](TOI/Bootstrap.R)

<br>   

#### Group coursework

The course work is different for MATH35600 and MATHM0019. The course work is to be completed in groups of three, to provide experience of team-working. You must arrange to be in a team with two others on the **same** course code as you (MATH35600 or MATHM0019). The coursework will be handed out on XXX. You should be sure to attend this lecture to pick up the coursework and register your work group (or to make sure that another group member did so for you). 
  
The 2018 course work is here: 

* [MATH35600 practical](TOI/M35600-18.pdf) 
* [MATHM0019 practical](TOI/M0019-18.pdf)
* [Example of a nice practical report](TOI/MA35600-nice-report.pdf) This is nice because it is well structured, convincingly argued and targets the intended audience given in the assignment sheet well, and the work itself is well done. It is not intended to be used as a template for writing a report.

<br>

#### Software

During the course we will use the R statistical software and the rjags package in particular. See the [CRAN webpage](https://cran.r-project.org/) to install R on your own computer. Before installing the rjags package, you will need to install the JAGS standalone software on your computer. See the installation instructions for different operating systems can be found [here](https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/).
